config/routes.rb
RottenMangoes::Application.routes.draw do
  root to: 'movies#index'

  resources :movies do 
    resources :reviews, only: [:new, :create, :destroy]
  end

  get '/search' => "movies#index" 

  resources :users, only: [:new, :create, :show]
  resources :session, only: [:new, :create, :destroy]

  namespace :admin do
    resources :users
  end
end

app/models/movie.rb
class Movie < ActiveRecord::Base

  has_many :reviews
  mount_uploader :image, ImageUploader

  validates :title,
    presence: true
  validates :director,
    presence: true
  validates :runtime_in_minutes,
    numericality: { only_integer: true }
  validates :description,
    presence: true
  validates :release_date,
    presence: true

  validate :release_date_is_in_the_past


  scope :search, lambda { |search, runtime|
    
    if search
      search = "%#{search.to_s.downcase}%"     
    else
      search = ""
    end

    sql = "LOWER(title) LIKE ? OR LOWER(director) LIKE ?"
    
    case runtime.to_i
    when 1 then sql += " AND runtime_in_minutes < 90"
    when 2 then sql += " AND runtime_in_minutes BETWEEN 90 AND 120"
    when 3 then sql += " AND runtime_in_minutes > 120"
    end
    
    where(sql, search, search)
  }


  def review_average
    if reviews.size > 0
      reviews.sum(:rating_out_of_ten)/reviews.size 
    else
      0
    end
  end

  protected

  def release_date_is_in_the_past
    if release_date.present?
      errors.add(:release_date, "should be in the past") if release_date > Date.today
    end
  end

end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :user
  belongs_to :movie

  validates :user,
    presence: true
  validates :movie,
    presence: true
  validates :text,
    presence: true

  validates :rating_out_of_ten,
    numericality: { only_integer: true }
  validates :rating_out_of_ten,
    numericality: { greater_than_or_equal_to: 1 }
  validates :rating_out_of_ten,
    numericality: { less_than_or_equal_to: 10 }

end

app/models/user.rb
class User < ActiveRecord::Base

  has_many :reviews

  has_secure_password

  validates :email,
    presence: true

  validates :firstname,
    presence: true

  validates :lastname,
    presence: true

  validates :password,
    length: { in: 6..20 }, on: :create

  def full_name
    "#{firstname.capitalize} #{lastname.capitalize}"
  end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  
  def index
    if current_user.admin
      @users = User.all.page(params[:page]).per(10)
    else
      flash[:alert] = "You must be an Admin to view the Users page!"
      redirect_to movies_path
    end
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to admin_users_path
    else
      render :new
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])

    if @user.update_attributes(user_params)
      redirect_to admin_users_path
    else
      render :edit
    end
  end

  def destroy
    @user = User.find(params[:id])
    
    UserMailer.delete_email(@user).deliver_later

    @user.reviews.each do |review|
      review.destroy
    end
    @user.destroy

    flash[:notice] = "User #{@user.full_name} deleted from database"
    redirect_to admin_users_path
  end

  protected

  def user_params
    params.require(:user).permit(:email, :firstname, :lastname, :admin, :password, :password_confirmation)
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  protected

  def restrict_access
    if !current_user
      flash[:alert] = "You must log in."
      redirect_to new_session_path
    end
  end

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user
  
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  def index
    if params[:search] || params[:runtime]
      @movies = Movie.search(params[:search],params[:runtime])
      flash[:notice] = "Search results shown below"
    else
      @movies = Movie.all
    end
  end

  def show
    @movie = Movie.find(params[:id])
  end

  def new
    @movie = Movie.new
  end

  def edit
    @movie = Movie.find(params[:id])
  end

  def create
    @movie = Movie.new(movie_params)

    if @movie.save
      redirect_to movies_path, notice: "#{@movie.title} was submitted successfully!"
    else
      render :new
    end
  end

  def update
    @movie = Movie.find(params[:id])

    if @movie.update_attributes(movie_params)
      redirect_to movies_path(@movie)
    else
      render :edit
    end
  end

  def destroy
    @movie = Movie.find(params[:id])
    @movie.destroy
    redirect_to movies_path
  end


  protected

  def movie_params
    params.require(:movie).permit(:title, :director, :runtime_in_minutes, :description, :poster_image_url, :image, :release_date, :remote_image_url)
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  
  before_filter :restrict_access
  before_filter :load_movie

  def new
    @review = @movie.reviews.build
  end

  def create
    @review = @movie.reviews.build(review_params)
    @review.user_id = current_user.id

    if @review.save
      redirect_to @movie, notice: "Review created successfully"
    else
      render :new
    end
  end

  protected

  def load_movie
    @movie = Movie.find(params[:movie_id])
  end

  def review_params
    params.require(:review).permit(:text, :rating_out_of_ten)
  end

end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:email])

    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to movies_path, notice: "Welcome back, #{user.firstname}!"
    else
      flash.now[:alert] = "Log in failed..."
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to movies_path, notice: "Adios!"
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:email])

    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to movies_path, notice: "Welcome back, #{user.firstname}!"
    else
      flash.now[:alert] = "Log in failed..."
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to movies_path, notice: "Adios!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      session[:user_id] = @user.id # auto log in
      redirect_to movies_path, notice: "Welcome aboard, #{@user.firstname}!"
    else
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
  end

  protected

  def user_params
    params.require(:user).permit(:email, :firstname, :lastname, :password, :password_confirmation)
  end  
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movies_helper.rb
module MoviesHelper

  def formatted_date(date)
    date.strftime("%b %d, %Y")
  end

  def duration_select_options
    [
      ["~ duration ~", 0],
      ["Under 90 minutes", 1],
      ["Between 90 \& 120 minutes", 2],
      ["Over 120 minutes", 3]
    ]
  end

  def get_movie(id)
    Movie.find(id)
  end

  def movie_title(id)
    get_movie(id).title
  end

end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper  
end

app/views/admin/users/_search.html.erb
<div class="form-group center">
  <%= form_tag "/search", method: "get", html: { class: "form-horizontal center" } do %>  
        <div class="input-group">
          <span>
            <%= search_field_tag :search, params[:search], placeholder: "Search movie, director, more...", class: "form-control", id: "sizing-addon1" %>  
          </span>
          <span class="input-group-btn">
            <%= submit_tag "search", class: "btn btn-default" %>
          </span>
        </div>
  <% end %>

</div>

app/views/admin/users/_user_form.html.erb
<%= form_for [:admin, @user] do |f| %>
  <% if @user.errors.any? %>
    <div>
      <%= pluralize(@user.errors.count, "error") %> prevented the account from being created:
      <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div>
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div>
    <%= f.label :firstname, "First Name" %><br>
    <%= f.text_field :firstname %>
  </div>
  <div>
    <%= f.label :lastname, "Last Name" %><br>
    <%= f.text_field :lastname %>
  </div>
  <div>
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </div>
  <div>
    <%= f.label :password_confirmation %><br>
    <%= f.password_field :password_confirmation %>
  </div>
  <div>
    <%= f.label :admin, "Admin User" %>
    <%= f.check_box :admin %>
  </div>
  <div><%= f.submit "Submit" %></div>
<% end %>

app/views/admin/users/edit.html.erb
<br/>
<div class="row">
  <div class="col-sm-5">
    <div class="well">
      <%= link_to "Back to all users", admin_users_path %>
      
      <h2>Edit this user</h2>
      <%= render 'user_form' %>
    </div>
  </div>
</div>

app/views/admin/users/index.html.erb
<br/>
<div class="well">
  <h1>Rotten Mangoed Users</h1>

  <%= paginate @users %><br/>
  <%= link_to 'Create New User', new_admin_user_path %>
  <div class="table-responsive">
    <table class="table" id="users_list">
      <thead>
        <tr>
          <th>First Name</th>
          <th>Last Name</th>
          <th>Email</th>
          <th>Admin</th>
          <th>Created At</th>
          <th>Updated At</th>
          <th colspan="2"></th>
        </tr>  
      </thead>
      <tbody>
        <% @users.each do |user| %>
          <tr>
            <td><%= user.firstname %></td>
            <td><%= user.lastname %></td>
            <td><%= user.email %></td>
            <td><%= user.admin %></td>
            <td><%= formatted_date(user.created_at) %></td>
            <td><%= formatted_date(user.updated_at) %></td>
            <td><%= link_to 'edit', edit_admin_user_path(user) %></td>  
            <td><%= link_to 'delete', "/admin/users/#{user.id}", method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>    
      </tbody>
    </table>
  </div>
</div>

app/views/admin/users/new.html.erb
<br/>
<div class="row">
  <div class="col-sm-5">
    <div class="well">
      <%= link_to "Back to all users", admin_users_path %>

      <h2>Create new user</h2>
      <%= render 'user_form' %>
    </div>
  </div>
</div>

app/views/layouts/_header.html.erb
<header>
  <div class="row top">
    <div class="col-md-3 text-left">
      <h4><strong><%= link_to "ROTTEN MANGOED", movies_path %></strong></h4>
    </div>
    <div class="col-md-6">
      <%= render 'search' %>
    </div>
    <div class="col-md-3 text-right">
    <h4>
        <% if current_user %>
          Hi, <%= current_user.firstname.capitalize %> (<%= link_to "Log out", session_path("current"), method: :delete %>) (<%= link_to "Admin", admin_users_path %>)
        <% else %>
          <%= link_to "Log In", new_session_path %> | <%= link_to "Sign Up", new_user_path %>
        <% end %>
        
        </h4>
    </div>
  </div>
</header>

app/views/layouts/_search.html.erb
<div class="form-group center">
  <%= form_tag "/search", method: "get", html: { class: "form-horizontal center" } do %>  
        <div class="input-group">
          <span>
            <%= search_field_tag :search, params[:search], placeholder: "Search movie, director, more...", class: "form-control", id: "sizing-addon1" %>  
          </span>
          <span class="input-group-btn">
            <%= submit_tag "search", class: "btn btn-default" %>
          </span>
        </div>
  <% end %>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rotten Mangoed</title>

    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>

    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>

    <%= csrf_meta_tags %>
  </head>
  <body>
    <div class="background-image"></div>
    <%= render 'layouts/header' %>
    <div class="container">
      <div class="row text-center" id="flash-msgs">
        <% flash.each do |key,value| %>
          <%= content_tag(:div, value) %>
        <% end %>      
      </div>
      <%= yield %>
    </div>
  </body>
</html>

app/views/movies/_form.html.erb
<%= form_for @movie, html: { multipart: true }, class: "form-horizontal" do |f| %>
  <% if @movie.errors.any? %>
    <div>
      <%= pluralize(@movie.errors.count, "error") %> prevented this movie from being submitted:
      <ul>
        <% @movie.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group">
    <%= f.label :title, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :title, placeholder: "Title", class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :release_date, class: "col-sm-2 control-label"  %>
    <div class="col-sm-10">
      <%= f.date_field :release_date, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :director, class: "col-sm-2 control-label"  %>
    <div class="col-sm-10">
      <%= f.text_field :director, placeholder: "Director", class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :runtime_in_minutes, class: "col-sm-2 control-label"  %>
    <div class="col-sm-10">
      <%= f.number_field :runtime_in_minutes, placeholder: "Runtime in minutes", class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :description, class: "col-sm-2 control-label"  %>
    <div class="col-sm-10">
      <%= f.text_area :description, placeholder: "Description", class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :remote_image_url, "Image URL:", class: "col-sm-2 control-label"  %>
    <div class="col-sm-10">
      <%= f.text_field :remote_image_url, placeholder: "Image URL", class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.file_field :image %>
    </div>
  </div>
  <div class="form-group">
    <%= f.submit "Submit", class: "btn btn-primary" %> 
  </div>
<% end %>

app/views/movies/_movie.html.erb
<div class="col-sm-3">
  <div class="card">
    <%= link_to image_tag(movie.image_url.to_s, class: "movie-img card-img-top", alt: "Card image cap"), movie_path(movie) %>
    <div class="card-block">
      <h3 class="card-title"><%= link_to movie.title, movie_path(movie) %></h3>
      <p class="card-text">
        <h4>Dir. <%= movie.director %></h4>
        <h5><%= movie.runtime_in_minutes %> minutes</h5>
        <h5>Release Date: <%= formatted_date(movie.release_date) %></h5>
        <p><%= movie.description %></p>
        <p>Average Rating: <%= movie.review_average %>/10</p>
      </p>
    </div>
  </div>
</div>

app/views/movies/_search.html.erb
<div class="form-group center">
  <%= form_tag "/search", method: "get", html: { class: "form-horizontal center" } do %>  
        <div class="input-group">
          <span>
            <%= search_field_tag :search, params[:search], placeholder: "Search movie, director, more...", class: "form-control", id: "sizing-addon1" %>  
          </span>
          <span class="input-group-btn">
            <%= submit_tag "search", class: "btn btn-default" %>
          </span>
        </div>
  <% end %>

</div>

app/views/movies/edit.html.erb
<br/>
<div class="row">
  <div class="well">
    <%= link_to "\< Back to this movie", movie_path(@movie) %>
    <h2>Edit this movie.</h2>
    <%= render 'form' %>
  </div>
</div>

app/views/movies/index.html.erb
<h2 class="text-center adder"><%= link_to "Submit a movie!", new_movie_path %></h2>
<div class="row">
  <% @movies.each_with_index do  |movie, index| %>

    <%= render partial: "movie", locals: {movie: movie} %>

    <% if (index+1) % 4 == 0 && (index+1) > 0  %>
      </div>  
      <div class="row">
    <% end %>
  <% end %>
</div>

app/views/movies/new.html.erb
<br/>
<div class="row">
  <div class="well">
    <h2>Submit a movie!</h2>
    <%= render 'form' %>
  </div>
</div>

app/views/movies/show.html.erb
<br/>
<div class="row well">
  <div class="col-sm-6">
    <%= link_to image_tag(@movie.image_url.to_s), movie_path(@movie) %>
  </div>
  <div class="col-sm-6">
    <h1><%= @movie.title %></h1>
    <h2><small>(<%= link_to "edit", edit_movie_path(@movie) %>, <%= link_to "delete", movie_path(@movie), method: :delete, confirm: "You sure?" %>)</small></h2>
    <h3><%= formatted_date(@movie.release_date) %></h3>
    <h4>Dir. <%= @movie.director %> | <%= @movie.runtime_in_minutes %> minutes</h4>
    <p><%= @movie.description %></p>

    <hr>

    <h3>Reviews of <em><%= @movie.title %></em></h3>
    <% if current_user %>
      <p>Average Rating: <%= @movie.review_average %>/10</p>
      <% @movie.reviews.each do |review| %>
        <p><%= review.text %></p>
        <p><%= review.rating_out_of_ten %>/10</p>
        <small>- <%= link_to review.user.full_name, user_path(review.user) %></small><br/>
      <% end %>
      <p><%= link_to "Write a review!", new_movie_review_path(@movie) %></p>
    <% else %>
      <p>Please <%= link_to "log in", new_session_path %> to see reviews and add your own.</p> 
    <% end %>
  </div>
</div>

app/views/reviews/_search.html.erb
<div class="form-group center">
  <%= form_tag "/search", method: "get", html: { class: "form-horizontal center" } do %>  
        <div class="input-group">
          <span>
            <%= search_field_tag :search, params[:search], placeholder: "Search movie, director, more...", class: "form-control", id: "sizing-addon1" %>  
          </span>
          <span class="input-group-btn">
            <%= submit_tag "search", class: "btn btn-default" %>
          </span>
        </div>
  <% end %>

</div>

app/views/reviews/create.html.erb
<h1>Reviews#create</h1>
<p>Find me in app/views/reviews/create.html.erb</p>

app/views/reviews/new.html.erb
<br/>
<div class="well">  
  <%= link_to "Back to movie", movie_path(@movie) %><br/>

  <h2>Write a review of <em><%= @movie.title %></em>.</h2>

  <%= form_for([@movie, @review]) do |f| %>
    <% if @review.errors.any? %>
      <div>
        <%= pluralize(@review.errors.count, "error") %> prevented the review from being saved:
        <ul>
          <% @review.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div>
      <%= f.label :text %><br>
      <%= f.text_area "text" %>
    </div>
    <div>
      <%= f.label :rating_out_of_ten %><br>
      <%= f.number_field :rating_out_of_ten %>
    </div>
    <div><%= f.submit "Submit" %></div>
  <% end %>
</div>

app/views/session/_search.html.erb
<div class="form-group center">
  <%= form_tag "/search", method: "get", html: { class: "form-horizontal center" } do %>  
        <div class="input-group">
          <span>
            <%= search_field_tag :search, params[:search], placeholder: "Search movie, director, more...", class: "form-control", id: "sizing-addon1" %>  
          </span>
          <span class="input-group-btn">
            <%= submit_tag "search", class: "btn btn-default" %>
          </span>
        </div>
  <% end %>

</div>

app/views/session/create.html.erb
<h1>Sessions#create</h1>
<p>Find me in app/views/sessions/create.html.erb</p>

app/views/session/new.html.erb
<br/>
<div class="well">
  <h1>Log In</h1>
  <%= form_tag session_index_path do %>
    <div>
      <%= label_tag :email %><br/>
      <%= text_field_tag :email %>
    </div>
    <div>
      <%= label_tag :password %><br/>
      <%= password_field_tag :password %>
    </div>
    <div><%= submit_tag "Log In" %></div>
  <% end %>
</div>

app/views/users/_search.html.erb
<div class="form-group center">
  <%= form_tag "/search", method: "get", html: { class: "form-horizontal center" } do %>  
        <div class="input-group">
          <span>
            <%= search_field_tag :search, params[:search], placeholder: "Search movie, director, more...", class: "form-control", id: "sizing-addon1" %>  
          </span>
          <span class="input-group-btn">
            <%= submit_tag "search", class: "btn btn-default" %>
          </span>
        </div>
  <% end %>

</div>

app/views/users/_user_form.html.erb
<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div>
      <%= pluralize(@user.errors.count, "error") %> prevented the account from being created:
      <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div>
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div>
    <%= f.label :firstname, "First Name" %><br>
    <%= f.text_field :firstname %>
  </div>
  <div>
    <%= f.label :lastname, "Last Name" %><br>
    <%= f.text_field :lastname %>
  </div>
  <div>
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </div>
  <div>
    <%= f.label :password_confirmation %><br>
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="form-group">
    <%= f.submit "Submit" %>
  </div>
<% end %>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/new.html.erb
<br/>
<div class="well">
  <h1>Sign Up</h1>
  <%  %>
  <%= render 'user_form' %>
</div>

app/views/users/show.html.erb
<br/>
<div class="well">  
  <h1>USER PROFILE</h1>

  <h2>Name: <%= @user.full_name %></h2>
  <h2>Email: <%= @user.email %></h2>

  <hr/>
  <h2>REVIEWS</h2>
  <% if @user.reviews.any? %>
    <% @user.reviews.each do |review| %>
      <div>
        <h3><%= link_to movie_title(review.movie_id), movie_path(get_movie(review.movie_id)) %></h3>      
        <p><%= review.text %></p>
        <p>Rating: <%= review.rating_out_of_ten %>/10</p>

        <p>Created at: <%= formatted_date(review.created_at) %></p>

      </div>
      <hr/>
    <% end %>
  <% end %>
</div>